### ISSUE TITLE
Fix styling in button

### ISSUE THREAD

**Issue by sergio222-dev** [sergio222-dev/ztools-2#5]
The current style for Button is 
```css
.side_button {
    font-family: 'Roboto', sans-serif;
    background-color: #244564;
    color: white;
    border: transparent;
    border-radius: 5px;
    font-size: 8.5px;
    font-weight: 400;
    padding: 5px 20px 5px;
    padding-right: 125px;
    padding-left: 10px;
    max-width: 100px;
    max-height: 25px;
    min-width: 60px;
    min-height: 20px;
    white-space: nowrap;
    text-align: left;
    margin-bottom: 2px;
    
}

.side_button:focus {
    background-color: #3674a7;
    box-shadow: 0px 0px 0px 1px #b3cfe6;
    -webkit-box-shadow: 0px 0px 0px 1px #b3cfe6;
    -moz-box-shadow: 0px 0px 0px 1px #b3cfe6;
}
.side_button:hover {
    background-color: #3674a7;
    // box-shadow: 0px 0px 0px 1px #b3cfe6;
    // -webkit-box-shadow: 0px 0px 0px 1px #b3cfe6;
    // -moz-box-shadow: 0px 0px 0px 1px #b3cfe6;
}
 ```

it should be 
```scss
.side_button {
    font-family: 'Roboto', sans-serif;
    background-color: #244564;
    color: white;
    border: transparent;
    border-radius: 5px;
    font-size: 8.5px;
    font-weight: 400;
    padding: 5px 20px 5px;
    padding-right: 125px;
    padding-left: 10px;
    max-width: 100px;
    max-height: 25px;
    min-width: 60px;
    min-height: 20px;
    white-space: nowrap;
    text-align: left;
    margin-bottom: 2px;

 &:focus {
    background-color: #3674a7;
    box-shadow: 0px 0px 0px 1px #b3cfe6;
    -webkit-box-shadow: 0px 0px 0px 1px #b3cfe6;
    -moz-box-shadow: 0px 0px 0px 1px #b3cfe6;
}
 &:hover {
    background-color: #3674a7;
    // box-shadow: 0px 0px 0px 1px #b3cfe6;
    // -webkit-box-shadow: 0px 0px 0px 1px #b3cfe6;
    // -moz-box-shadow: 0px 0px 0px 1px #b3cfe6;
  }
}
```
